version: '3.8'

services:
  query-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app

  streamlit-ui:
    image: python:3.10-slim
    command: sh -c "pip install streamlit requests && streamlit run /app/frontend/streamlit_app.py --server.port 8501 --server.enableCORS false"
    ports:
      - "8501:8501"
    volumes:
      - .:/app