aws_profile           = "default"
s3_bucket_name        = "querycopilot-bucket"
athena_database_name  = "querycopilot_db"
athena_table_name     = "copilot_events"
athena_output_location = "s3://querycopilot-bucket/athena-results/"